environment:
  matrix:
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "7"

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm@latest
  - node --version
  - npm --version
  - npm ci

test_script:
  - npm test
